# Generated by Django 4.0.1 on 2022-02-01 08:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=56)),
                ('last_name', models.CharField(max_length=56)),
                ('customer_needs', models.CharField(choices=[("I'm interested in this", "I'm interested in this"), ("I'd like to know your best price for this", "I'd like to know your best price for this"), ("I'd like to test drive this", "I'd like to test drive this"), ("I'd like a history report for this", "I'd like a history report for this")], max_length=256)),
                ('car_title', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=56)),
                ('message', ckeditor.fields.RichTextField(blank=True)),
                ('user_id', models.IntegerField(blank=True)),
                ('car_id', models.IntegerField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
