# Generated by Django 4.0.1 on 2022-02-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='customer_needs',
            new_name='customer_need',
        ),
    ]
