# Generated by Django 4.0.1 on 2022-02-01 16:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_customer_needs_contact_customer_need'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('message', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
