# Generated by Django 4.0.1 on 2022-01-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mil_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(),
        ),
    ]
